# Generated by Django 3.0.2 on 2020-02-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('basicinfo', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedDataRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('is_last', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disk1_used', models.FloatField(default=0.0, verbose_name='卡1')),
                ('disk2_used', models.FloatField(default=0.0, verbose_name='卡2')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collecteddatarecorditem_related', to='basicinfo.Station', verbose_name='所属台站')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommmonInstrumentRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('is_last', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('instrument', models.ForeignKey(limit_choices_to={'is_model': False}, on_delete=django.db.models.deletion.CASCADE, related_name='by_used_histories', to='instruments.Instrument', verbose_name='更换仪器记录')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commmoninstrumentrecorditem_related', to='basicinfo.Station', verbose_name='所属台站')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsertDiskRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('is_last', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disk1_size', models.FloatField(default=0.0, verbose_name='卡1')),
                ('disk2_size', models.FloatField(default=0.0, verbose_name='卡2')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertdiskrecorditem_related', to='basicinfo.Station', verbose_name='所属台站')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentEntityRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('is_last', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instrument_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_used_histories', to='instruments.InstrumentEntity', verbose_name='更换测震仪器记录')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumententityrecorditem_related', to='basicinfo.Station', verbose_name='所属台站')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('is_last', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('altitude', models.FloatField(default=0.0, verbose_name='高程')),
                ('geo_desciription', models.TextField(blank=True, verbose_name='位置描述')),
                ('lithology_description', models.TextField(blank=True, verbose_name='岩性描述')),
                ('other_info', models.TextField(blank=True, verbose_name='其他信息')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationrecorditem_related', to='basicinfo.Station', verbose_name='所属台站')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commmoninstrumentrecord',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='commmoninstrumentrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='insertdiskrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='instrumententityrecord',
            name='instrument_entity',
        ),
        migrations.RemoveField(
            model_name='instrumententityrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='locationrecord',
            name='station',
        ),
        migrations.AlterField(
            model_name='record',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('LocationRecordItem', 'InstrumentEntityRecordItem', 'CommmonInstrumentRecordItem', 'InsertDiskRecordItem', 'CollectedDataRecordItem')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.DeleteModel(
            name='CollectedDataRecord',
        ),
        migrations.DeleteModel(
            name='CommmonInstrumentRecord',
        ),
        migrations.DeleteModel(
            name='InsertDiskRecord',
        ),
        migrations.DeleteModel(
            name='InstrumentEntityRecord',
        ),
        migrations.DeleteModel(
            name='LocationRecord',
        ),
    ]
