# Generated by Django 3.0.3 on 2020-02-29 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_auto_20200229_1006'),
        ('logs', '0002_auto_20200224_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterstatuscheck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afterstatuscheck',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beforestatuscheck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beforestatuscheck',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selection', '勘选'), ('online', '在线'), ('suspend', '暂停'), ('offline', '下线')], default='selection', max_length=50, verbose_name='状态')),
                ('begined_at', models.DateTimeField(verbose_name='状态改变时间')),
                ('remark', models.TextField(blank=True, verbose_name='说明')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.Station')),
            ],
        ),
    ]
