# Generated by Django 3.0.3 on 2020-02-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200229_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationStatus',
        ),
    ]
